version: '3.8'

services:
  web:
    build: 
      context: ./Let_em_cook
    ports:
      - "5000:5000"
    volumes:
      - ./Let_em_cook:/app
    environment:
      - FLASK_APP=front.py
      - FLASK_ENV=development
    stdin_open: true
    tty: true